AWSTemplateFormatVersion: 2010-09-09
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: AppUserPool 
      UsernameAttributes: 
        - email
      Schema: 
        - Name: email
          AttributeDataType: String
          Required: true
      Policies: ー
        PasswordPolicy:
          MinimumLength: 12
      AdminCreateUserConfig: 
        AllowAdminCreateUserOnly: true
        UnusedAccountValidityDays: 7
      AutoVerifiedAttributes: 
        - email
      AccountRecoverySetting: 
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool 
      ClientName: MyUserPoolClient 
      GenerateSecret: true 
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      AccessTokenValidity: 60 
      IdTokenValidity: 60 
      RefreshTokenValidity: 30 
      ExplicitAuthFlows: 
        - ALLOW_USER_SRP_AUTH 
        - ALLOW_REFRESH_TOKEN_AUTH
      ReadAttributes: 
        - email
      WriteAttributes: 
        - email
